// <auto-generated />
using System;
using Course.CloudNativeDev.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Course.CloudNativeDev.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260525211445_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Course.CloudNativeDev.Api.Entities.Attendee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("GenderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("JobRoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LAstNAme")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<Guid>("ReferalSourceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GenderId");

                    b.HasIndex("JobRoleId");

                    b.HasIndex("ReferalSourceId");

                    b.ToTable("Attendee");
                });

            modelBuilder.Entity("Course.CloudNativeDev.Api.Entities.Gender", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Genders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e51f98bb-d9ee-4496-b195-fb6891046f7d"),
                            Name = "Male"
                        },
                        new
                        {
                            Id = new Guid("51ba96aa-167e-4cff-bca4-0c68d1555086"),
                            Name = "Female"
                        });
                });

            modelBuilder.Entity("Course.CloudNativeDev.Api.Entities.JobRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("JobRoles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e51f98bb-d9ee-4496-b145-fb6891046f7d"),
                            Name = "Manager"
                        },
                        new
                        {
                            Id = new Guid("51ba96aa-167e-4cff-bca4-0c68f1555086"),
                            Name = "Supervisor"
                        },
                        new
                        {
                            Id = new Guid("51ba96aa-167e-4cff-bca4-0c68f1555034"),
                            Name = "Sales"
                        },
                        new
                        {
                            Id = new Guid("51ba96aa-167e-4cff-bca4-0c68f1655034"),
                            Name = "Operations"
                        });
                });

            modelBuilder.Entity("Course.CloudNativeDev.Api.Entities.ReferalSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ReferalSources");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e51f98bb-d9ee-5496-b145-fb6891046f7d"),
                            Name = "Internet Advertisement"
                        },
                        new
                        {
                            Id = new Guid("51ba96aa-167e-4cff-bcb4-0c68f1555086"),
                            Name = "Television"
                        },
                        new
                        {
                            Id = new Guid("51ba96aa-167e-4cff-bca4-0c68f1665034"),
                            Name = "Newspaper Article"
                        },
                        new
                        {
                            Id = new Guid("51ba96aa-167e-4cff-bca4-0c68f4655034"),
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("Course.CloudNativeDev.Api.Entities.Attendee", b =>
                {
                    b.HasOne("Course.CloudNativeDev.Api.Entities.Gender", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Course.CloudNativeDev.Api.Entities.JobRole", "JobRole")
                        .WithMany()
                        .HasForeignKey("JobRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Course.CloudNativeDev.Api.Entities.ReferalSource", "ReferalSource")
                        .WithMany()
                        .HasForeignKey("ReferalSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gender");

                    b.Navigation("JobRole");

                    b.Navigation("ReferalSource");
                });
#pragma warning restore 612, 618
        }
    }
}
